### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rpavlik** [joedevivo/vscode-circuitpython#61] opened 2021-09-28 17:02 UTC
There have been a number of new boards since the last release, and there's also my improvements to the stubs that have been merged but not released. Would be great to get a new release out. Let me know how I can help.

**Comment by wmerkens** [comment] 2021-10-11 01:21
Thanks for the re-write of the builds-stubs.sh, one thing I noticed is that it's not exiting from the python venv.

    # get out of venv
    deactivate

It complains about deactivate not being found. I had to comment it out and replace it with "exit"

Also, why do you
rm -rf stubs/board

I find that causes issues in code for detection of the board module.

**Comment by joedevivo** [comment] 2022-03-26 15:14
I actually just had to remove the `deactivate` when moving to GitHub Actions, and confirmed that it is unnecessary because of the sub-shell. This is all in 0.1.16. Thanks!

**Closed** 2022-03-26 15:15 UTC
Labels: bug
